on: [push, pull_request]
name: Build

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Install .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x
            - name: Install Rust
              uses: dtolnay/rust-toolchain@nightly

            - name: Build
              run: ./package.ps1

            - name: Upload GDWeave
              uses: actions/upload-artifact@v3
              with:
                  name: GDWeave
                  path: ./local/GDWeave
            - name: Upload Thunderstore package
              uses: actions/upload-artifact@v3
              with:
                  name: thunderstore
                  path: ./thunderstore

